### ISSUE TITLE
Dark background for clips.twitch.tv

### ISSUE THREAD

**Issue by MattiSony** [night/BetterTTV#1269]

**Comment by Trubbel** [comment]
Made this a while ago, been using the browser extension _Stylish_ to make it look like the BetterTTV theme. You can use this until they decide to update BetterTTV.


```CSS
body,
html {
background: rgb(20,20,20) ! important;
}

/* make video background black and removes box shadow */
.clip-wrap {
background: rgb(0, 0, 0) ! important;
box-shadow: none ! important;
}

.broadcaster-info .broadcaster-info__title,
a[class="curator-link js-curator-link"] {
color: #d3d3d3 ! important;
}
.svg-logo_twitch {
fill: #fff ! important;
}
a[class^="broadcaster-info__name-link"],
a[class^="broadcaster-info__game-link"],
.curator {
color: #999 ! important;
}
span[class^=" broadcaster-info__game"] {
color: #8c8c8c ! important;
}

/* removes unnecessary spacing */
#clip-meta {
margin-top: 0px ! important;
}
```
