### ISSUE TITLE
Messages with Mentioning "@USERNAME"

### ISSUE THREAD

**Issue by SoWhoYou** [night/BetterTTV#2487]
In the Normal Theme your're setting...
```CSS
.chat-messages .chat-line.highlight .from {
    color: #000 !important!
}
```
In the Dark Theme you're setting...
```CSS
.chat-messages .chat-line.highlight .from {
    color: #FFF !important!
}
```

Why is this being set? Please remove this.
It's very annoying seeing peoples names be black/white every time they mention my name in chat.

I don't understand why you need to change the color of the names the message is coming from, just because they are being mentioning me. It's super annoying and it looks like trash.

![asdfasdfasdf](https://cloud.githubusercontent.com/assets/5152979/26527673/d9131034-4366-11e7-89d8-2a4b423946cf.png)
