### ISSUE TITLE
Bot Badges turn into normal Moderator Badges when moused over

### ISSUE THREAD

**Issue by LeotomasMC** [night/betterttv#3168]
When you have BTTV installed, Nightbot, and 2 other bots per channel can have a Bot Badge, and this replaces the normal Moderator Badge. However, when you put your mouse over a Bot Badge, it turns back into a normal Moderator Badge

**Comment by theyuvalshor** [comment]
This has been a thing for a long time, it's so little I haven't even thought of reporting it as an issue.

**Comment by night** [comment]
same issue as #2939 .. unlikely to be fixed anytime soon, if ever

**Comment by EhsanKia** [comment]
Maybe slightly hacky but the following fixes it:

```css
/* Turn the badge container an inline-flex box */
.chat-line__message > span:first-of-type {
    display: inline-flex;
    vertical-align: bottom;
}

/* Set the BTTV badge to a high order so it's always last */
.bttv-chat-badge {
    order: 10;
}
```

This also happens to fix the inconsistent spacing between the bttv badges.
