### ISSUE TITLE
Make "Hide Twitch Extensions" Hide Extension Taskbar as well.

### ISSUE THREAD

**Issue by krezack** [night/BetterTTV#3188]
Add the following css to /src/modules/video_player/style.css to also hide the taskbar when Hide Twitch Extensions is turned on.

```css
.bttv-hide-player-extensions {
  .extension-taskbar {
    display: none !important;
  }
}
```
