### ISSUE TITLE
Idea: Enhanced Theater Mode

### ISSUE THREAD

**Issue by Far-Se** [night/betterttv#5204]
Preview:

https://user-images.githubusercontent.com/20853986/153699788-02655b76-7f93-480a-adef-754297c01255.mp4

When someone move mouse to left border, the sidebar and headbar will become visible, there is a timeout for headbar so people have time to move mouse up.

Also online users and timestamp is cloned on bottom left to know when stream started and also current viewers.

Here is my code for it:
```js
// Show users and timestamp in bottom left corner.
setInterval(function(){
    let e = document.querySelector('.metadata-layout__support + div > div:nth-child(2)');
    if(e)
    {
        let text = e.innerHTML;
        let x = document.querySelector('#channelTime');
        if(x)x.innerHTML = text;
        else document.querySelector('body').insertAdjacentHTML('beforeend',`<div id="channelTime">${text}</div>`);
    }
}, 1000);

//Detect mouse and toggle sidebar and headbar.
window.hovering = 0;
setTimeout( function() {
    let el = document.querySelector('#sideNav');
    el.onmouseenter = () => {
        window.hovering = 1;
        document.querySelector('nav[data-a-target]').style.zIndex = 999999
    };

    document.querySelector('nav[data-a-target]').onmouseenter = () => {
        window.hovering = 1;
    }
    el.onmouseleave = document.querySelector('nav[data-a-target]').onmouseleave = () => {
        window.hovering = 0;
        setTimeout( () => {
            if(window.hovering == 0)
            {
                document.querySelector('nav[data-a-target]').style.zIndex = 1
            }
        },700);
    }
}, 2000);
```
Here is the extra css:
```css
div#sideNav:after {
    content: "";
    position: absolute;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
    background: transparent;
    z-index: 99999;
}

div#sideNav {
    position: relative;
}
div#sideNav:hover:hover .side-nav{
    display:block;
    z-index:99999999;
    position: fixed;

    top: 50px;
    padding-top: 0px;
}

.tw-flex.tw-flex-column .tw-flex.tw-flex-column.tw-flex-grow-0.tw-flex-shrink-1.tw-justify-content-start .tw-mg-l-1 > .tw-align-items-center.tw-flex.tw-justify-content-end> div:first-child
{
    position:fixed;
    left: 0px;
    z-index: 99999;
    bottom: 0px;
    filter: grayscale(0.4) opacity(0.5);
}
div#sideNav {
    margin-bottom: 110px;
    height: 50%;
}
div#sideNav:before {
    content: "";
    background: #1f1f23;
    z-index: -1;
    bottom: 0;
    top: 0;
    height: 100vh;
    position: absolute;
    width: 50px;
}

:root {
    --zindex: 1;
}

nav.top-nav.tw-flex-shrink-0 {
    z-index: var(--zindex);
}

div#sideNav:hover {
    --zindex: 999999;
}

div#channelTime {
    position: absolute;
    bottom: 0;
    left: 0;
    z-index: 99999;
    font-weight:bold;
	opacity:0.7;
	zoom:0.9;

    pointer-events: none;
}
div#channelTime b {
    display: inline-block;
}

div#channelTime b:first-child {
    padding: 0px 10px;
    color: var(--color-text-live)  !important;
}
body #channelTime >div >div >div:nth-child(2) {
    display: none !important;
}
```
