### ISSUE TITLE
Allow the navbar 'nav_section' to always be expanded

### ISSUE THREAD

**Issue by tsunami643** [night/BetterTTV#848]
A lot of useful links for broadcasters, such as the Dashboard and Video Manager are always hidden in the leftbar's extra menu and won't show until the dropdown is expanded.

An option to either keep the section always expanded, or choose which links show in the collapsed version (instead of the default Profile, Following, Messages) would be nice.

**Comment by Trubbel** [comment]
I have been using Stylish for this for quite some time now, here is the css if you can't wait for the update.

```CSS
/* expands the navbar */
#large_nav .content .nav_section ul.extra-menu {
height: 102px ! important;
}

/* removes the show more button */
#large_nav .content .nav_section .left-col-dropdown.collapsed,
#large_nav .content .nav_section .left-col-dropdown {
display: none ! important;
}
```
